apiVersion: v1
kind: Pod
metadata:
  name: coherence-test-pod
  annotations:
    schedulerName: "lambda-g"
spec:
  schedulerName: lambda-g-manual  # This stops the default scheduler from stealing it
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
